name: Yezzey testing

on:
  push:
    branches: [ "OPENGPDB_STABLE", "OPENGPDB_6_27_STABLE", "MDB_6_25_STABLE_YEZZEY" ]
  pull_request:
    branches: [ "OPENGPDB_STABLE", "OPENGPDB_6_27_STABLE", "MDB_6_25_STABLE_YEZZEY" ]

jobs:

  build_and_run_yezzey:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Yezzey
        run: docker compose -f docker/yezzey/docker-compose.yaml run --build --remove-orphans yezzey
      
      
